### ISSUE TITLE
random issues i found

### ISSUE THREAD

**Issue by monkey1352** [MichaelEpicA/VMBattleRoyale#1]
thought id put this in here because why not

1
when u set a username and then quit the host application
then start the host application again and try to set the username it says that its already taken
fix: delete username from list after disconnect

2
also maybe related to that other issue
the server keeps counting for every client connected but it doesnt go down when it disconnects
fix: decrement counter after disconnect

3
when username is already taken you dont get reprompted to set the username
fix: reprompt

4
hacking progress increments whether or not the word was correct
fix: only increment if word was correct

5
Spelling error at line 55 of the vm setup
probably some more spelling errors at other parts of the project that i didnt catch
fix: change Your to You're

probably gonna do some of these myself
also probably shouldve done these in seperate issues but i didnt really feel like it
though i will for any further issues that i put here

**Comment by monkey1352** [comment]
- 4 done in commit 56ca502cd02cd6f8c9682de2e50b86e1c95b6ef0

- 5 done in commit 8d4525ab4dcc4f186477ef64eee70254baa7e9be

ill leave the rest to @MichaelEpicA because im too stupids!

**Comment by monkey1352** [comment]
Consequense of  1 or/and 2:
when you start the host, set a username and then close the host
your user stays
if you repeat that 3 times
you can start a game with only 1 client actually connected

**Comment by MichaelEpicA** [comment]
bruh 5 is just lmfao

**Comment by MichaelEpicA** [comment]
3 is not a bug and meant to happen.

**Comment by MichaelEpicA** [comment]
I think all of these bugs are fixed! I've tested all of them except 3, and everythings good!

**Comment by MichaelEpicA** [comment]
Reprompting was added. All bugs are fixed.
