### ISSUE TITLE
The win condition doesn't actually work.

### ISSUE THREAD

**Issue by MichaelEpicA** [MichaelEpicA/VMBattleRoyale#4]
Writing this down, but in testing, I don't think the Win condition ever gets triggered. We will need to add this.

**Comment by nicholasb3** [comment]
sex

**Comment by MichaelEpicA** [comment]
Hopefully fixed in 902e377ac0b2d937ce6cdc4d6f24c5e6953e5b1c

**Comment by MichaelEpicA** [comment]
Hopefully fixed in eb47c26338e63491193c2538195c53e046b72693
